### ISSUE TITLE
Possible ETA on 0.5.0 release?

### ISSUE THREAD

**Issue by dave-r12** [cternes/openkeepass#14]
Hello, I was wondering if you had a rough idea of the release timing around 0.5.0? I'm currently using the SNAPSHOT version and leveraging the write aspect. Thanks for writing this BTW

**Comment by cternes** [comment]
I'm not sure when 0.5.0 will be released but it should be finalized in the next months. There are still some open tests to do and I have to check if the API works well enough.

**Comment by dave-r12** [comment]
Alright, thanks
