### ISSUE TITLE
Entry UUID is not read from file

### ISSUE THREAD

**Issue by dpishchukhin** [cternes/openkeepass#15]
During refactoring between 0.4.2 and 0.5.0-SNAPSHOT entry UUID is not read from input file.

**Comment by cternes** [comment]
What do you mean, can you provide an example? The unit tests seem to be green.

**Comment by dpishchukhin** [comment]
OK. I found the issue on my side. thanks. 

Any release dates for 0.5?

**Comment by cternes** [comment]
The release should be in the next days
