### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by frozenice** [cternes/openkeepass#16]
Add a `LICENSE` file to the GItHub repo. This helps people who want to use openkeepass or contribute to it, they can directly see what they are allowed to do.

I see you are using Apache 2.0 on [Maven](http://mvnrepository.com/artifact/de.slackspace/openkeepass/0.5.0). You should add either the [full text](http://www.apache.org/licenses/LICENSE-2.0.txt) of the license (up to "END OF TERMS AND CONDITIONS") or the short version (under "APPENDIX", replace the placeholders) to the repo.
For bonus points add a link to [tldrlegal](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)) at the top.

I plan to use openkeepass myself and have one or two things I'd like to contribute. :)

**Comment by cternes** [comment]
Adding a license file to the repo makes sense. However, in the pom file the license is already mentioned and it should be sufficient as it is right now.
