### ISSUE TITLE
Add support of master password together with key file 

### ISSUE THREAD

**Issue by dpishchukhin** [cternes/openkeepass#18]
Now API supports or master password either key file. KeePass tools (original and keepassx) have a possibility to set them together.

**Comment by cternes** [comment]
Supported with commit bb53512ab21

**Comment by dpishchukhin** [comment]
Any plans to release this new feature?

**Comment by cternes** [comment]
No, not yet. I'm gathering more features first.

**Comment by HoppeAndreas** [comment]
works fine when KeePass generates a new key file, because this is XML.
But according to the KeePass home page you can use other files as well :

>Key Files
> **File Type and Existing Files**. KeePass can generate key files for you, however you can also use any other, already existing file (like JPG image, DOC document, etc.).

but that raises a SAXParseException as it is not valid XML
Maybe it is possible to support other keyfiles as well ?

**Comment by cternes** [comment]
I will have a look at it.

**Comment by cternes** [comment]
Binary key files are now supported with 0f8724246b533a7207

**Comment by Footmau** [comment]
Is there possibility to write with key file?
