### ISSUE TITLE
When writing a KeePassFile instance in the file, the password of the entry is made in illegal state.

### ISSUE THREAD

**Issue by yososs** [cternes/openkeepass#30]
This behavior There are two problems.

* Writing twice the instance to the file, the password is incorrect state
* Can not be compared to the input instance and the output instance for verification

Test Code

	@Test
	public void testKeePass() throws IOException{

		//Create DB
		{
			final KeePassFile keePassFile = new KeePassFileBuilder("testDB").build();
			final FileOutputStream out = new FileOutputStream("xxx.kdbx");
			try {
				KeePassDatabase.write(keePassFile, "test", out);
			} finally {
				IOUtils.closeQuietly(out);
			}
		}
		//Open / Add Entry / Write / Assert
		{
			File fileX = new File("xxx.kdbx");
			File fileY = new File("yyy.kdbx");
			final FileInputStream in = new FileInputStream(fileX);
			final FileOutputStream out = new FileOutputStream(fileY);
			try {
				final KeePassFile keePassFile = KeePassDatabase.getInstance(fileX).openDatabase("test");
				UUID uuid = UUID.randomUUID();
				Entry enrty = new EntryBuilder(uuid).title("title").password("password").build();
				new GroupBuilder(keePassFile.getRoot().getGroups().get(0)).addEntry(enrty).build();

				KeePassDatabase.write(keePassFile, "test", out);
				
				// Password Wrong?
				Assert.assertEquals("password", enrty.getPassword());
				Assert.assertEquals("password", keePassFile.getRoot().getGroups().get(0).getEntries().get(0).getPassword());
				
			} finally {
				IOUtils.closeQuietly(in);
				IOUtils.closeQuietly(out);
			}
		}
	}

**Comment by cternes** [comment]
You code is quite confusing.What are you trying to achieve?

Actually the following line does nothing, because you're not using the result of the build method:

     new GroupBuilder(keePassFile.getRoot().getGroups().get(0)).addEntry(enrty).build();

Maybe it could help if you would take a look into the unit tests of the project to get familiar with the api.

**Comment by yososs** [comment]
I open an existing database file, and some update, want to write to a new file. Test code is already read.

Did you look at the results that were actually run the test code written by me?

`new GroupBuilder(keePassFile.getRoot().getGroups().get(0)).addEntry(enrty).build();`

In fact, the new entry is registered in the database file.

However, like the write method it has side effects, made to state the password is encoded in the entry of KeePassFile instance.

The correct update how I want you to explain in index.md.

**Comment by cternes** [comment]
Thanks, I've got your point. I agree that entries should not be modified during writing.

**Comment by yososs** [comment]
This fix does not pass my test code.
I will pull request.

**Comment by cternes** [comment]
@yososs I've implemented your test in method `shouldEnsureThatEntriesAreNotModifiedDuringWriting()`. Can you tell me why this does method does not fulfill your requirement?

**Comment by yososs** [comment]
Because it does not pass the following line, which I wrote, it was investigated.

` Assert.assertEquals("password", keePassFile.getRoot().getGroups().get(0).getEntries().get(0).getPassword());
`
Since this line is to pass and to comment out the write () method, it is obvious there are still side effects.

* Looking at the original correction code, but have created a clone, not a clone instance to the input of the toXML method.

> return new KeePassDatabaseXmlParser().toXml(keePassFile).toByteArray();

```

    private byte[] marshallXml(KeePassFile keePassFile, KeePassHeader header) {
        KeePassFile clonedKeePassFile = new GroupZipper(keePassFile).cloneKeePassFile();

        ProtectedStringCrypto protectedStringCrypto = Salsa20.createInstance(header.getProtectedStreamKey());
        new ProtectedValueProcessor().processProtectedValues(new EncryptionStrategy(protectedStringCrypto), clonedKeePassFile);

        return new KeePassDatabaseXmlParser().toXml(keePassFile).toByteArray();
    }
```




```
    @Test
    public void shouldEnsureThatEntriesAreNotModifiedDuringWriting () {
        // Open DB
        . Final KeePassFile keePassFile = KeePassDatabase.getInstance ( "target / test-classes / testDatabase.kdbx") openDatabase ( "abcdefg");
        Group generalGroup = keePassFile.getGroupByName ( "General");

        // Add entry
        ... Entry entry = new EntryBuilder (UUID.randomUUID ()) title ( "title") password ( "password") build ();
        new GroupBuilder (generalGroup) .addEntry (entry) .build ();

        // Compare password in current DB
        Assert.assertEquals (. Entry.getPassword (), generalGroup.getEntryByTitle ( "title") getPassword ());

        // Get origin passwords
        List <String> originPasswords = new ArrayList <String> ();
        List <Entry> entries = keePassFile.getEntries ();
        for (Entry e: entries) {
            originPasswords.add (e.getPassword ());
        }

        // Write to new DB
        KeePassDatabase.write (keePassFile, "abcdefg", "target / test-classes / testDatabase_new.kdbx");

        // Get final passwords
        List <String> finalPasswords = new ArrayList <String> ();
        for (Entry e: entries) {
            finalPasswords.add (e.getPassword ());
        }

        // Compare original passwords with final ones
        assertThat (finalPasswords, is (originPasswords));

        

        
        // Add by Yos ---------------------------------------------- -----------------------------
        List <String> finalPasswords2 = new ArrayList <String> ();
        List <Entry> entries2 = keePassFile.getEntries ();
        for (Entry e: entries2) {
        finalPasswords2.add (e.getPassword ());
        }

        assertThat (originPasswords, is (finalPasswords2));
        
    }
```
