### ISSUE TITLE
Usecase: editing an entry

### ISSUE THREAD

**Issue by ronsmits** [cternes/openkeepass#36]
With the current setup, editing an entry is a challenge. One needs the entry to show the current information but you need an entry builder to actually update the entry. GUI wise this is kind of a hell toggling between two different objects to handle this. 

Is this usecase not in view for this project? or is there another pattern in use here?

**Comment by cternes** [comment]
Editing an entry is of course a valid use-case. The domain objects are mostly immutable which has a few advantages. But I also know that handling immutable objects in java can be a challenge. 

If you want to build a GUI around KeePass it could make sense that you don't use the domain objects directly in your GUI but instead use some kind of intermediate layer that is fully mutable. If the user has finished his work and want to save the changes in the KeePass file, you could then use the builders to transfer the changes into the domain model and write the KeePass file. 

What do you think about this?

**Comment by ronsmits** [comment]
Yeah that is the solution I am already working on.  It makes sense in my case as I am can make it a kotlin class and javaFX enabled ;)

**Comment by cternes** [comment]
Ok, let me know if you need some help or if you have trouble with the api.
