### ISSUE TITLE
Compatibility of Java6 Do you need?

### ISSUE THREAD

**Issue by yososs** [cternes/openkeepass#39]
Compatibility of Java6 Do you need?

* Java 6 is already support has been ended.

* Java7 By the above, can be used StandardCharsets that was introduced in Java7,
UnsupportedEncodingException check is not required in String.getBytes ( "UTF-8").

Java6
```
         try {
             return hash (text.getBytes ( "UTF-8"));
         } Catch (UnsupportedEncodingException e) {
             throw new UnsupportedOperationException ( "The encoding 'UTF-8' is not supported", e);
         }

```

Java7+
```
         return hash (text.getBytes (StandardCharsets.UTF_8));`
```

**Comment by cternes** [comment]
This is out of question at the moment. 

Java 6 is a stratetic architectural decision, because many companies are still forced to use Java 6.
