### ISSUE TITLE
Entries created with KeeFox 1.4.7 extension are not decrypted correctly

### ISSUE THREAD

**Issue by Raprp** [cternes/openkeepass#4]
Hi,

I created a brand new database on KeePass 2.28 and I am able to see the entries that I create manually.

But when I save an entry using KeeFox 1.4.7 on firefox, the password is not decrypted correctly using openkeepass:

Title: Sample Entry #2 Password: 12345
Title: Sign in - Google Accounts Password: 1�

The first is an entry created on KeePass and the second created on KeeFox addon.

Cheers,

**Comment by cternes** [comment]
What version of openkeepass are you using?
Can you add a sample database which could not be correctly decrypted?

**Comment by Raprp** [comment]
Just forked the master.

I will send a pull request with the file.

Cheers,

**Comment by cternes** [comment]
Fixed with commit b945e4674ac2366fa9d2c1dd1a329b5badf9b674

Please pull from master.

**Comment by Raprp** [comment]
Now it decrypts my database correctly. Thanks.
