### ISSUE TITLE
Correction to Project Description and Readme

### ISSUE THREAD

**Issue by jorabin** [cternes/openkeepass#47]
Congratulations on this project. Would you mind, though, correcting the project description and Readme which incorrectly state

"A java library for reading and writing KeePass databases. It is the only java library that supports KeePass 2.x database files."

There are several projects here on GitHub that similarly offer Java support for Keepass 2.x data files, mine, [KeepassJava2](https://github.com/jorabin/KeePassJava2), is one of them :-)

**Comment by cternes** [comment]
At the time of creating this project openkeepass was the only library which was able to support KeePass 2.x. In the meantime there are other projects which support this format, so I will update the description.

**Comment by jorabin** [comment]
Thanks for taking this on board.
