### ISSUE TITLE
Edit a loaded Database and save destroy passwords.

### ISSUE THREAD

**Issue by timia2109** [cternes/openkeepass#49]
Hey whats the best way to add a entry to a database without changing the existing structure?

I try:
```java
KeePassFile keeFile = KeePassDatabase.getInstance( file ).openDatabase( password );
keeFile.getEntries().add(new EntryBuilder(name)
                .username(user)
                .password(pass)
                .build());
KeePassDatabase.write(keeFile, pass, new FileOutputStream( file ) );
```
It dosn't add the new key and destroy all existing passwords. On next load of the database they are all wrong.

**Comment by timia2109** [comment]
More information: try on Android. Load existing DB from KeePass (original Windows) => Works
Add entry and save. Then all passwords are lost

**Comment by cternes** [comment]
Which version are you using? Have you tried with the latest master commit?

**Comment by timia2109** [comment]
I'm using version 0.6.0. I will try that with the last commit later.

**Comment by ronsmits** [comment]
if you look at the code of KeepassFile you will see that getEntries is a list containing the accumulation of alle entries in all groups:

    /**
     * Retrieves a list of all entries in the KeePass database.
     *
     * @return a list of all entries
     * @see Entry
     */
    public List<Entry> getEntries() {
        List<Entry> allEntries = new ArrayList<Entry>();

        if (root != null) {
            getEntries(root, allEntries);
        }

        return allEntries;
    }

I dont think adding an entry to that list is what is intended. I always add an entry to a group:

    Group group = new GroupBuilder("group1").build();
    group.getEntries().add(new EntryBuilder().title("test").build();
    KeepassFile keepassFile = KeePassFileBuilder("test_file").build();
    keepassFile.getRoot().getGroups().add(group);

I use this all the time without any problems both with 0.6.0 and with the current master which I hope will be released soon :+1:

**Comment by timia2109** [comment]
Let's say I got a KeePassFile from my computer with groups and passwords where I want to add a password without change the existing things how I do that? Is it possible to add that to the loaded DB? Or must I rebuild anything?

**Comment by ronsmits** [comment]
That would be done as follows(I wrote all the code in kotlin, so this is a rough translation but it gives you the idea
    
    keepassFile = KeePassDatabase.getInstance(absolutePath).openDatabase(password);
    firstGroup = keepassFile.getRoot().getGroups().get(0);
    firstGroup.getEntries().add(new EntryBuilder().title("test").build();
    File file = new File("testfile.kdbx");
    KeepassDatabase.write(keepassFile, "password", new FileOutputStream(file))l

**Comment by timia2109** [comment]
So I try that on this way.

Here are my methods:
```java
    private String key;
    private List<Entry> logins;
    private KeePassFile keedb;
    private File keeFile;

    public File getKeeFile() {
        if (keeFile == null)
            //Utils.getAppDir(ctx) returns File
            keeFile = new File(Utils.getAppDir(ctx), "kee.kdbx");
        return keeFile;
    }

    public void loadKeePass(String pass) throws Exception {
        //For testing
        if (pass.equals("0")) {
            getKeeFile().delete();
            return;
        }

        keedb = KeePassDatabase.getInstance(getKeeFile().getAbsolutePath()).openDatabase(pass);

        logins = keedb.getEntries();
        key = pass+""; //Clone String instance to be sure
    }

    //Save action
    @Override
    public void run() {
        try {
            KeePassDatabase.write(keedb, key, new FileOutputStream(getKeeFile()));
        } catch (Exception e) {
            Utils.notify(ctx, "Fehler Passwörter", "Konnte Passwort DB nicht speichern!", PASS_DB_SAVE_ERROR_NOTIFY);
            Utils.logError(ctx, e, false);
        }
    }

    public void addLogin(String name, String user, String pass) throws Exception {
        Entry newEntry = new EntryBuilder(name)
                .username(user)
                .password(pass)
                .build();

        changed = true;
        keedb.getRoot().getGroups().get(0).getEntries().add(newEntry);
        notifyDataSetChanged(); //We are in a base adapter
    }

    @Override
    public void notifyDataSetChanged() {
        logins = keedb.getEntries();
        super.notifyDataSetChanged();
    }
```

After I add an other Entry, save and close the file and reopen it you cann see on the link all passwords are destroyed. While DB is loaded I can see the Entry is there.
http://imgur.com/a/J4Mv2

**Comment by ronsmits** [comment]
I took your code and made a gist with working unit test. Your code is correct, If there is corruption it seems to come for the android side. You can find the gist here : https://gist.github.com/ronsmits/7fd219b76cf8829fd9127e222224d6c7

**Comment by cternes** [comment]
@timia2109 Please try with the **latest version 0.6.1** as in v0.6.0 there was a bug only on Android devices which could lead to this issue.

**Comment by timia2109** [comment]
I don't understand. I try this by updating to 0.6.1 with 
```
compile ('de.slackspace:openkeepass:0.6.1') {
        exclude module: 'stax'
        exclude module: 'stax-api'
        exclude module: 'xpp3'
    }
```
Also dosn't work. Then I try it with use jitpack and grap the source direct from github with 
```
repositories {
			...
			maven { url 'https://jitpack.io' }
		}
dependencies {
	        compile 'com.github.cternes:openkeepass:openkeepass-0.6.1'
	}
```
Also same result. Try it on two phones (Android 6 & Android 7) => same result.

I try to write on the existing file is that false? 😢

**Comment by cternes** [comment]
I tried out your code on Android and it works fine for me. I guess there is something wrong with your existing keepass file. 

You could rule that out by creating a new keepass file directly with openkeepass and modify that. 
If that works, the problem is indeed your keepass file. How was your keepass file created, with official Keepass and if yes which version?

Could you upload the keepass file you're using (change passwords/userames first!)?

**Comment by timia2109** [comment]
I create a new KeePass File with the offical Windows Programm. After creating I copy it to the phone and open it. Add a password and the passwords are destroyed. Then I try to copy the file to my SMB Share and ES Fileexplorer was unable to copy the file. So maybe it's destroyed.

I'm not the Android expert, but run() runs in a new Thread while Activity is paused. Must I close the FileOutputStream or is that done by OpenKeePass?

Here is the file that I loaded https://drive.google.com/open?id=0B7LoEfRgjKteeVlBcEIteGNMZFk Password is "test"

**Comment by cternes** [comment]
Sorry @timia2109  but I cannot reproduce your problem. I've tried your code together with your Keepass file and everything works quite well even on Android. No corruption happened. Tried with Android 6.0 (API 23).

I've used this very simple Android program:

    package com.example.test;

    import android.content.Context;
    import android.os.Environment;
    import android.support.v7.app.AppCompatActivity;
    import android.os.Bundle;
    import android.util.Log;

    import java.io.ByteArrayOutputStream;
    import java.io.File;
    import java.io.FileOutputStream;
    import java.nio.charset.Charset;
    import java.util.List;
    import java.util.zip.GZIPOutputStream;

    import de.slackspace.openkeepass.KeePassDatabase;
    import de.slackspace.openkeepass.domain.Entry;
    import de.slackspace.openkeepass.domain.EntryBuilder;
    import de.slackspace.openkeepass.domain.Group;
    import de.slackspace.openkeepass.domain.GroupBuilder;
    import de.slackspace.openkeepass.domain.KeePassFile;
    import de.slackspace.openkeepass.domain.KeePassFileBuilder;
    import de.slackspace.openkeepass.util.ByteUtils;

    public class MainActivity extends AppCompatActivity {

        @Override
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);
            setContentView(R.layout.activity_main);

            testBug();
        }

        private void testBug() {
            File fileIn = new File(getApplicationContext().getFilesDir(), "testKeePass.kdbx");
            File fileOut = new File(getApplicationContext().getFilesDir(), "testKeePass_modified.kdbx");

            KeePassFile keedb = KeePassDatabase.getInstance(fileIn).openDatabase("test");

            Entry newEntry = new EntryBuilder("something")
                    .username("A")
                    .password("xxx")
                    .build();

            keedb.getRoot().getGroups().get(0).getEntries().add(newEntry);

            try {
                KeePassDatabase.write(keedb, "test", new FileOutputStream(fileOut));

                KeePassFile db = KeePassDatabase.getInstance(fileOut).openDatabase("test");
                Entry entry = db.getEntryByTitle("something");
                String user = entry.getUsername();
                String passwd = entry.getPassword();
                System.out.println("User:" + user);
                System.out.println("Pwd:" + passwd);
            } catch (Exception e) {
                System.err.println("Exception happened. " + e);
            }
        }
    }

**Comment by timia2109** [comment]
I found my error. After trying to create another file and move it to position fails, I log everything. And the error was very simple and my fault.

    @Override
    protected void onPause() {
        //Run after onBackPressed....
        super.onPause();
        loginAdapter.unload();
    }

    @Override
    public void onBackPressed() {
        loginAdapter.unload();
        super.onBackPressed();
    }

There was two threads that both try to save, so that was the issue.

I'm very sorry to stole your time and I'm very helpful for your help!
Thanks!
