### ISSUE TITLE
Reading / Writing Entry attachments

### ISSUE THREAD

**Issue by blakesmith** [cternes/openkeepass#50]
I'd like to be able to read / write entry attachments from a KeePass database (I often attach long keys and certificates this way), but am unable to find any calls that point at this functionality.

1. Is there anything I'm missing? Perhaps a different name for the feature?
2. If not, would you accept patches / PRs adding this functionality?
3. If you'll accept patches, any pointers on where to start? I haven't done a deep dive on the KeePass database format (is there a spec somewhere?), but can start familiarizing myself with the openkeepass code base in the meantime.

Thanks!

**Comment by cternes** [comment]
1. You're right, this functionality is currently missing.
2. Sure, after I've reviewed the PR.
3. Unfortunately there is no specification of the KeePass database format out there (at least not that I would know). You could start by looking at the decrypted xml structure to get familiar with the database format.

**Comment by dwmolina** [comment]
Hi blakesmith.

I'd like to read and write entry attachments too.

Did you work it out?

**Comment by blakesmith** [comment]
@dwmolina I haven't yet - got sidetracked with other things. Feel free to take a crack if you'd like.
