### ISSUE TITLE
Could not decrypt keepass file. Master key wrong?

### ISSUE THREAD

**Issue by hdiwan** [cternes/openkeepass#51]
KeepassX and KeepassXC are able to decrypt the database with the same keyfile and openkeepass is not. I don't have the bandwidth at this time to go through the source, but will have some in 12 hours. Meantime, I'm leaving this here as a reminder. Will update as I discover more.

**Comment by cternes** [comment]
Any news, yet? Otherwise I will close for inactivity.

**Comment by hdiwan** [comment]
That's the news, I wasn't able to look into it further

**Comment by cternes** [comment]
Can you provide the database and the keyfile to unlock?

**Comment by hdiwan** [comment]
Sure, the files are attached to this comment. I had to add .txt to them to let them through the github upload filter. Strip it off for testing.
[keyfile.txt](https://github.com/cternes/openkeepass/files/1033995/keyfile.txt)
[4Testing.kdbx.txt](https://github.com/cternes/openkeepass/files/1033996/4Testing.kdbx.txt)

**Comment by cternes** [comment]
A simple test worked pretty fine for me. Could not see any issues.

    @Test
    public void testOpenWithKeyFile() throws FileNotFoundException {
        FileInputStream file = new FileInputStream(ResourceUtils.getResource("4Testing.kdbx"));
        FileInputStream key = new FileInputStream(ResourceUtils.getResource("keyfile.txt"));

        KeePassFile db = KeePassDatabase.getInstance(file).openDatabase(key);

        Entry entry = db.getEntryByTitle("Test");
        System.out.println(entry.getPassword());
    }

**Comment by atoka93** [comment]
@cternes 
It happens to me as well.
Code to initialize:
```text
    private fun openPasswordDatabase(databaseFile: File, password: String) {
        errorTextView.text = ""
        thread(start = true) {
            try {
                val database = KeePassDatabase.getInstance(databaseFile).openDatabase(password)

                activity?.runOnUiThread {
                    errorTextView.text = ""

                    // Start Activity
                }
            } catch (e: Exception) {
                Logger.d(e.message)
                activity?.runOnUiThread {
                    errorTextView.text = e.message
                }
            }
        }
    }
```
Database:
[dummy.kdbx.txt](https://github.com/cternes/openkeepass/files/1725417/dummy.kdbx.txt)
Password:
123456asdfgh
