### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by murthychandrappa** [cternes/openkeepass#52]
Hi,

I started using this library in one of my use case where my team members access password for different servers stored in the keepass file frequently. In my testing after calling the below code probably after 10times my micro services crashes. I have 1GB allocated to my service.

KeePassDatabase.getInstance(keepassFileinputStream).openDatabase("password",keyfileInputStream);

Is this something you could check and fix this memory leak?

Thanks,
Murthy

**Comment by cternes** [comment]
I've tried your use-case by running `getInstance()` in a loop and monitored the memory allocation. It looks pretty normal for me. 

![Openkeepass Memory Allocation](http://imgur.com/a/ZT6mT)

How big is your keepass file? Have you profiled your application and you're sure the cause is openkeepass?
