### ISSUE TITLE
Password is gibberish when opening file last saved by KeeWeb

### ISSUE THREAD

**Issue by billwi** [cternes/openkeepass#53]
I use KeeWeb on my computer to handle passwords. However, in the android app, if I open that database, the password is displayed as gibberish. If I open the same database in any other app, it works fine. If I open it elsewhere and save it, then open it via this API, it opens fine.

Database last saved by keeweb attached. Remove the .txt extension (Master password is `github`)
[GithubIssue.kdbx.txt](https://github.com/cternes/openkeepass/files/1157603/GithubIssue.kdbx.txt)

Keeweb: https://keeweb.info/

**Comment by cternes** [comment]
Tried with KeeWeb and worked fine. I've used the following process:

- Tried to open with OpenKeepass
- Opened with KeeWeb, changed password and closed KeeWeb
- Tried to open with OpenKeepass again --> worked fine and new password is also visible

Did you follow another another process? What does "password is gibberish" mean?

**Comment by billwi** [comment]
Sorry, should have been more clear.

The issue is the password field of any entry, not the overall database's password. So I can create an entry called "GitHub account", with username "user" and password "password" in keeweb, but if I try and open it in openkeepass, it shows random ASCII/Unicode characters.

**Comment by cternes** [comment]
Yes, I know it's about the entries password, but I'm still unable to reproduce the issue. If I create a new entry using keeweb and then opening it in openkeepass it still works fine.

1. On which system are you using this process, do you have any Android involved into this? 
2. The attached GithubIssue.kdbx does it contain the "gibberish" password?

**Comment by billwi** [comment]
I'm using Ubuntu 16.04 with keeweb and Android marshmallow on my Galaxy S5.

Yes, that file has the issue.


On Aug 27, 2017 10:44 PM, cternes <notifications@github.com> wrote:

Yes, I know it's about the entries password, but I'm still unable to reproduce the issue. If I create a new entry using keeweb and then opening it in openkeepass it still works fine.

On which system are you using this process, do you have any Android involved into this?The attached GithubIssue.kdbx does it contain the "gibberish" password?

**Comment by cternes** [comment]
Ok, and the issue occurs only on Android, right? Have you written your own app to open the keepass file there?

**Comment by billwi** [comment]
Yes to both questions.


On Aug 27, 2017 11:21 PM, cternes <notifications@github.com> wrote:

Ok, and the issue occurs only on Android, right? Have you written your own app to open the keepass file there?

**Comment by cternes** [comment]
Mhh, tried with Android emulator and the keepass file from above, works fine for me. I guess you're using the latest version 0.6.1, right?

Any more hints like Android version or something?
