### ISSUE TITLE
getUsername does not resolve referenced field's value

### ISSUE THREAD

**Issue by chrisnelson** [cternes/openkeepass#58]
We are using KeePass for tracking service account credentials per application in our environment. It is possible, we will have the same user/pass for multiple applications--but our system requires a unique KeePass entry. As a result, we've tried out adding new entries that have the Username and Password fields referenence an existing/master entry. In the KeePass UI, you'll see the value for the stored Username (or Password or whatever field you're adding reference too) is something in the form of {REF:U@I:36F89B594FD7664E89E62E8CE220129A}. Once we started doing that, our automation broke (that is using the OpenKeePass library) because the usernames & passwords returned weren't the linked values but the links themselves, ie: {REF:U@I:36F89B594FD7664E89E62E8CE220129A}. 

I've done my best to dig into the code and don't see any support for this concept. Is it possible to add the ability to resolve the value if an Entry has a linked reference? 

Example:
Title: Item 1, Username: masterUser, UUID 36F89B594FD7664E89E62E8CE220129A
Title: Item 2, Username: {REF:U@I:36F89B594FD7664E89E62E8CE220129A}

When doing `database.getEntryByTitle("Item 2").getUsername();` it would be nice to have **masterUser** returned.

Thanks!

**Comment by cternes** [comment]
Interesting! I was not even aware that this feature exists :) I need to look into the concept to see how it should work. Depending on the required effort I will decide if I will support it.

**Comment by cternes** [comment]
This feature is now supported (only with UUID references). Hope this helps.
