### ISSUE TITLE
Some improvement ideas

### ISSUE THREAD

**Issue by hudeany** [cternes/openkeepass#59]
Hello cternes,

I stumbled over your great library while searching for a solution for a KeePass "Automatic Password Changer".
Found nothing, so I am writing one on my own now, using your library for storage in KeePass files.

Doing so I found some issues:
- Add a generated "private static final long serialVersionUID" to all of your own Exception classes (Eclipse shows warnings in case they are missing)
- Use char[] as password representation for security reasons (Passwords as String in memory are unsafe in JAVA, see also "String uniqueness in JAVA")
- Do not keep full file data in byte[] "KeePassDatabase.keepassFile" (might crash on huge file input streams, also this might be unlikely with password files)
- Make "KeePassDatabaseWriter.writeKeePassFile" and dependend methods static (they do not use any instance member variables of KeePassDatabaseWriter)
- Why are String constants like "Entry.PASSWORD" and others private? (Why not use a public enum for that constants?)
- Why not add a method "Entry.setPassword(String newPassword)" and other setter methods for the existing getter methods? (Workaround with .getProperties and .remove/.add seems inconvenient)

Maybe I come around with some more issues when I am done with my project, if you want to hear about them.

with kind regards
HuDeanY

**Comment by cternes** [comment]
Thanks for your findings. For most of them there is a good reason why it is implemented as it is, so I don't think I will change the implementation in the near future.
