### ISSUE TITLE
Trouble with reading of created by this library file.kdbx

### ISSUE THREAD

**Issue by KostyaM** [cternes/openkeepass#64]
Hello, I created a file.kdbx with your library. I added there an entry, group. All works great. I saved this file, opened it again in my app, all works great. But if i try to open this file by KeePassDroid I am getting an error:
![bpap1u8tpja](https://user-images.githubusercontent.com/33448856/42211674-ced2c1e0-7ebc-11e8-8017-9bc4c36ba5cd.jpg)

What went wrong?

Here is link for my kdbx file

https://vk.com/doc139236776_469854622?hash=93df14818ed1dad713&dl=918099d4e1c206eafc

The password is: 1

I will happy if you will fix this bug

**Comment by cternes** [comment]
Please ask the devs of KeePassDroid for help. I cannot debug KeePassDroid on my side.
