### ISSUE TITLE
EntryBuilder.iconData() strange behavior for me

### ISSUE THREAD

**Issue by KostyaM** [cternes/openkeepass#65]
Hello again)). Sorry, that I disturb you, but i can't understand, how does `Entry iconData(ByteArray) `works. I tried to save byte array of my own image, but after saving, i am getting another image (standard entry image "key"). It is some strange for me. What should i do, if I want to save my own image?

**Comment by KostyaM** [comment]
It seems like that when i am trying to save my entry, my icon data replaced by some another icon data, in my case this image:
![ex](https://user-images.githubusercontent.com/33448856/42959292-e8dad916-8b90-11e8-88c3-7858e7723364.jpg)

**Comment by KostyaM** [comment]
I am saving entry like so
`.addEntry(EntryBuilder(entry.label).username(entry.username).url(entry.url).password(entry.password).iconData(entry!!.icon).build())`

**Comment by cternes** [comment]
The correct usage is:

        CustomIcon customIcon = new CustomIconBuilder().uuid(iconUuid).data(customPng).build();
        CustomIcons customIcons = new CustomIconsBuilder().addIcon(customIcon).build();

        Meta meta = new MetaBuilder("iconTest").customIcons(customIcons).build();
        Entry entry1 = new EntryBuilder("1").customIconUuid(iconUuid).build();

**Comment by KostyaM** [comment]
And how can i retriev this icon? And where I need to use this: [Meta meta = new MetaBuilder("iconTest").customIcons(customIcons).build();](url).  And yes, thank you.

**Comment by cternes** [comment]
You need to write the meta header with your icons while writing the keepass file:

    Meta meta = new MetaBuilder("iconTest").customIcons(customIcons).build();
    KeePassFile keePassFile = new KeePassFileBuilder(meta).build();

Then you can retrieve the icon on an entry or group with:

    byte[] icon = entry.getIconData()

There is a test in the project which shows exactly this use case: `KeepassDatabaseWriterTest:shouldWriteDatabaseWithCustomIcon()`

**Comment by KostyaM** [comment]
Thanks I got it. Everything is working.
