### ISSUE TITLE
BouncyCastle <1.50 binary compatibility

### ISSUE THREAD

**Issue by gueugaie** [cternes/openkeepass#8]
BC 1.50 introduced a non backwards compatible change in `StreamCipher#processBytes`, which now returns an `int` instead of `void`.
This change is **source** compatible (meaning openkeepass can recompile without a change to BC 1.49 and less), but not **binary** compatible, one gets the following error : 

    java.lang.NoSuchMethodError: org.bouncycastle.crypto.engines.Salsa20Engine.processBytes([BII[BI)I

While not an issue with this implementation in and of itself, this forces applications to upgrade BouncyCastle to 1.50+, which can be expansive.

Would you consider a change (or a pull request) to refactor `Salsa20`, using a reflection based appraoch to mitigate the issue ?

I'm thinking something along the lines of : 

    import org.bouncycastle.crypto.engines.Salsa20Engine;

    public class Salsa20EngineAdapter extends Salsa20Engine {

    private static final String PROCESS_BYTES_METHOD = "processBytes";
    private static final Class<?>[] PROCESS_BYTES_ARG = new Class[] { byte[].class, Integer.TYPE, Integer.TYPE, byte[].class, Integer.TYPE };
  
    public void adaptProcessBytes(byte[] in, int inOff, int len, byte[] out, int outOff) {
      try {
        // BouncyCastle 1.50 and above
        super.processBytes(in, inOff, len, out, outOff);
      } catch (NoSuchMethodError e) {
        // In BC 1.49 and below, #processBytes() returns void instead of int, this breaks binary compatibilty
        // http://stackoverflow.com/a/3589948/2131074
        try {
          Method processBytesMethod = Salsa20Engine.class.getMethod(PROCESS_BYTES_METHOD, PROCESS_BYTES_ARG);
          processBytesMethod.invoke(this, in, inOff, len, out, outOff);
        } catch (Exception e1) {
          // Ignore e1, rethrow e
          throw e;
        }
      }
    }
  
    }

Reproducing the behaviour needs a separate project importing openkeepass, but excluding the BC dependency with an older version.

**Comment by gueugaie** [comment]
A few alternatives thoughts on how to solve this issue :

Falling back to `javax.crypto.Cipher`
------
This basically means changing the initialize method to :

	private void initialize(byte[] protectedStreamKey) {
		byte[] salsaKey = Sha256.hash(protectedStreamKey);
		try {
	    salsa20Engine = Cipher.getInstance("Salsa20", BouncyCastleProvider.PROVIDER_NAME);
	    salsa20Engine.init(Cipher.DECRYPT_MODE, new SecretKeySpec(salsaKey, "Salsa20"), new IvParameterSpec(Hex.decode(SALSA20IV)));
		} catch (Exception e) {
		  throw new RuntimeException(e);
		}
	}

But has the drawback of needing BouncyCastle to be registered as a Security Provider, something the current version does not need.

Providing alternate versions of the jar
--------------
One could alter the pom to provide two versions (with the appropriate qualifier). Each version would have (e.g.) its own profile, the profile defining the BC version against which openkeepass is compiled and an artifact qualifier, leading to the build of two distinct jars. Something along the lines of [this stackoverflow question](http://stackoverflow.com/questions/3092085/building-same-project-in-maven-with-different-artifactid-based-on-jdk-used)

**Comment by cternes** [comment]
I will have a look at it, the fallback seems interesting.

**Comment by cternes** [comment]
Fixed with commit 8f6c59309b7a7beb48510e02de127d353124cf26 by using security provider

**Comment by gueugaie** [comment]
Thanks for this solution :) :+1: 
At this point, this may be considered as a non issue, but you might want to call `Security.addProvider` only once (static initializer ?). This actually does not change much things, as the JVM's `SecurityProvider` essentially makes it a no-op of to add the same provider twice.
